import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Media {

    // the primary key (ID) is auto generated by ObjectDB
    @Id 
    @GeneratedValue 
    private Integer id = null;
    
    private Integer userId;
    private String realFileName;
    private String storedFileName;

    // a no argument constructor is required by JPA
    public Media() {
    }

    public Media(Integer userId, String realFileName, String storedFileName) {
        setUserId(userId);
        setRealFileName(realFileName);
        setStoredFileName(storedFileName);
    }

    // Getters and Setters
    public Integer getId() {
        return id;
    }

    public Integer getUserId() {
        return userId;
    }

    public String getRealFileName() {
        return realFileName;
    }

    public String getStoredFileName() {
        return storedFileName;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public void setRealFileName(String realFileName) {
        this.realFileName = realFileName.trim();
    }

    public void setStoredFileName(String storedFileName) {
        this.storedFileName = storedFileName.trim();
    }

    @Override
    public String toString() {
        return "Media {id=" + id + ", fileName='" + getRealFileName() + "'}";
    }
}